name: conundrum_car
description: App to control a remote control car for EGEN310 at Montana State University.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dartis: ^0.2.0
  logging: ^0.11.3+2
  wifi_iot:
      git: https://github.com/alternadom/WiFiFlutter.git
  font_awesome_flutter: ^8.2.0



flutter:
  uses-material-design: true
  assets:
    - assets/main_logo.png