name: conundrum_car
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  dartis: ^0.2.0
  logging: ^0.11.3+2
  wifi_iot:
      git: https://github.com/alternadom/WiFiFlutter.git
  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.2.0



flutter:
  uses-material-design: true

  assets:
    - assets/main_logo.png